export const ENV_KEYS = {
  ADMIN_API_KEY: 'ADMIN_API_KEY',
  PORT: 'PORT',
  CORS_ORIGIN: 'CORS_ORIGIN',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_NAME: 'DB_NAME',
  DB_USER: 'DB_USER',
  DB_PASSWORD: 'DB_PASSWORD',
} as const;

export type EnvKey = (typeof ENV_KEYS)[keyof typeof ENV_KEYS];

export const REQUIRED_ENV_KEYS: readonly EnvKey[] = [
  ENV_KEYS.ADMIN_API_KEY,
  ENV_KEYS.PORT,
  ENV_KEYS.CORS_ORIGIN,
  ENV_KEYS.DB_HOST,
  ENV_KEYS.DB_PORT,
  ENV_KEYS.DB_NAME,
  ENV_KEYS.DB_USER,
  ENV_KEYS.DB_PASSWORD,
];
