name: Lab 4 Helm Chart Grading

on:
  push:
    branches:
      - '**'

jobs:
  helm-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Setup KinD Cluster (for dry-run installation)
        uses: helm/kind-action@v1.9.0

      - name: Run Master Validation Script
        run: |
          chmod +x ./tests/lab4_test.sh
          ./tests/lab4_test.sh
